metricbeat.config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.period: 10s
    reload.enabled: true

metricbeat.max_start_delay: 10s

setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["172.28.1.2:9200"]

setup.kibana:
  host: "172.28.1.3:5601"

metricbeat.modules:

- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://sqlserver:1433"]
  username: sa
  password: Your_password123
  period: 10s

- module: elasticsearch
  metricsets:
    - node
    - node_stats
    - index
    - index_recovery
    - index_summary
    - shard
    - ml_job
  period: 10s
  hosts: ["http://172.28.1.2:9200"]

- module: kibana
  metricsets: ["status"]
  period: 10s
  hosts: ["172.28.1.3:5601"]
  basepath: ""
  enabled: true