FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY ./ ./

RUN dotnet restore "api/TheCatWebApi/TheCatWebApi.csproj"
RUN dotnet build "api/TheCatWebApi/TheCatWebApi.csproj" -c Release -o /app/build

RUN dotnet publish "api/TheCatWebApi/TheCatWebApi.csproj" -c Release -o /out
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS runtime
COPY --from=build /out .
ENTRYPOINT ["dotnet", "TheCatWebApi.dll"]